# Generated by Django 4.1.5 on 2024-01-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_follow_follows_follow_follows_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follows_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='network.follow'),
        ),
    ]
