# Generated by Django 4.1.5 on 2024-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_follow_follows_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follows_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='follows_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='network.follow'),
        ),
    ]
