# Generated by Django 4.1.5 on 2024-01-03 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_follow_follows_user_follow_follows_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follows_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='follows_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
