# Generated by Django 4.1.5 on 2024-01-03 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_follow_follows_user_follow_follows_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follows_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='follows_user',
            field=models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
