# Generated by Django 4.1.5 on 2024-01-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_follow_follows_user_follow_follows_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follows_user',
            field=models.ManyToManyField(null=True, related_name='followers', to='network.follow'),
        ),
    ]
